# Generated by Django 4.1.7 on 2023-02-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_menu_mstyle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '菜单管理', 'verbose_name_plural': '菜单管理'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='level',
            field=models.CharField(default='', max_length=150, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='mid',
            field=models.CharField(default='', max_length=150, verbose_name='mid'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='pid',
            field=models.CharField(default='', max_length=150, verbose_name='pid'),
        ),
    ]
