# Generated by Django 4.1.7 on 2023-02-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_menu_options_alter_menu_level_alter_menu_mid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='mclass',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='mdataoption',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='dataOption'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='mhref',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='href'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='msrc',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='src'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='mstyle',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='style'),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='nick_name',
            field=models.CharField(default='', max_length=50, verbose_name='单位名称'),
        ),
    ]
