# Generated by Django 4.1.7 on 2023-02-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_menu_mclass_alter_menu_mdataoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='mclass',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='class'),
        ),
    ]
