# Generated by Django 4.1.7 on 2023-02-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_menu_mclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='mdataoption',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='dataOption'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='mhref',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='href'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='msrc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='src'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='mstyle',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='style'),
        ),
    ]
