# Generated by Django 4.1.7 on 2023-02-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_menu_mdataoption_alter_menu_mhref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default='', max_length=12, verbose_name='pid')),
                ('mid', models.CharField(default='', max_length=12, verbose_name='mid')),
                ('addressShort', models.CharField(default='', max_length=150, verbose_name='地址简称')),
                ('addresAll', models.CharField(default='', max_length=150, verbose_name='地址全称')),
                ('level', models.IntegerField(verbose_name='级别')),
            ],
            options={
                'verbose_name': '行政区划表',
                'verbose_name_plural': '行政区划表',
            },
        ),
        migrations.AlterField(
            model_name='userbase',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='单位地址'),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话'),
        ),
    ]
