# Generated by Django 4.1.7 on 2023-02-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_region_id_alter_region_mid'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='region',
            name='addressShort',
            field=models.CharField(default='', max_length=50, verbose_name='地址简称'),
        ),
        migrations.AlterField(
            model_name='region',
            name='mid',
            field=models.IntegerField(verbose_name='mid'),
        ),
        migrations.AlterField(
            model_name='region',
            name='pid',
            field=models.IntegerField(verbose_name='pid'),
        ),
    ]
