# Generated by Django 4.1.7 on 2023-02-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_region_id_alter_region_addressshort_alter_region_mid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='id',
        ),
        migrations.AlterField(
            model_name='region',
            name='mid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='mid'),
        ),
    ]
