# Generated by Django 4.1.7 on 2023-02-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_id_region_mid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='mid',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='mid'),
        ),
        migrations.AlterField(
            model_name='region',
            name='pid',
            field=models.CharField(default='', max_length=12, verbose_name='pid'),
        ),
    ]
