# Generated by Django 4.1.7 on 2023-02-27 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='infant_stu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True, verbose_name='学生姓名')),
                ('card', models.CharField(max_length=18, null=True, verbose_name='学生身份证号')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('regaddress', models.CharField(max_length=100, null=True, verbose_name='户籍所在地')),
                ('resaddress', models.CharField(max_length=100, null=True, verbose_name='居住所在地')),
                ('regsch', models.CharField(max_length=100, null=True, verbose_name='意向学校')),
                ('tel', models.CharField(max_length=11, null=True, verbose_name='联系电话')),
            ],
            options={
                'verbose_name': '幼儿园入学意向调查表',
                'verbose_name_plural': '幼儿园入学意向调查表',
            },
        ),
        migrations.CreateModel(
            name='operation_stu_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=18, null=True, verbose_name='学生身份证号')),
                ('edittype', models.IntegerField(choices=[(0, '未上传资料或未提交'), (1, '提交待初审'), (2, '初审通过'), (3, '审核不通过（不允许再次提交）'), (4, '审核不通过（驳回修改)'), (5, '复审通过'), (6, '复审不通过')], default=0, verbose_name='操作状态')),
                ('names', models.CharField(max_length=11, null=True, verbose_name='操作人')),
                ('times', models.CharField(max_length=20, null=True, verbose_name='操作时间')),
                ('result', models.CharField(max_length=100, null=True, verbose_name='操作结果')),
                ('resultnotes', models.CharField(max_length=200, null=True, verbose_name='操作情况补充说明')),
            ],
            options={
                'verbose_name': '预登记情况操作日志',
                'verbose_name_plural': '预登记情况操作日志',
            },
        ),
        migrations.CreateModel(
            name='stu_grades',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='年级')),
                ('name', models.CharField(max_length=50, verbose_name='年级名称')),
            ],
            options={
                'verbose_name': '年级名称表',
                'verbose_name_plural': '年级名称表',
            },
        ),
        migrations.CreateModel(
            name='stu_schools',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='学校编号')),
                ('name', models.CharField(max_length=50, verbose_name='学校名称')),
            ],
            options={
                'verbose_name': '学校名称表',
                'verbose_name_plural': '学校名称表',
            },
        ),
        migrations.CreateModel(
            name='stu_school_grade',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('grade', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elementary.stu_grades')),
                ('school', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elementary.stu_schools')),
            ],
            options={
                'verbose_name': '学校年级名称总表',
                'verbose_name_plural': '学校年级名称总表',
            },
        ),
        migrations.CreateModel(
            name='stu_register_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True, verbose_name='学生姓名')),
                ('card', models.CharField(max_length=18, null=True, verbose_name='学生身份证号')),
                ('age', models.IntegerField(null=True, verbose_name='年龄')),
                ('jfr1name', models.CharField(max_length=20, null=True, verbose_name='监护人1姓名')),
                ('jfr1gx', models.PositiveSmallIntegerField(choices=[(2, '父亲'), (3, '母亲'), (4, '爷爷'), (5, '奶奶'), (6, '外公'), (7, '外婆'), (12, '亲哥'), (13, '亲嫂'), (14, '表哥'), (15, '表嫂'), (16, '堂哥'), (17, '堂嫂'), (18, '亲姐'), (19, '亲姐夫'), (20, '表姐'), (21, '表姐夫'), (22, '堂姐'), (23, '堂姐夫'), (24, '伯父'), (25, '伯母'), (26, '叔父'), (27, '婶母'), (28, '舅父'), (29, '舅母'), (30, '姨父'), (31, '姨母'), (32, '姑父'), (33, '姑母'), (34, '其他亲属'), (35, '非亲属')], verbose_name='监护人1与登记人关系')),
                ('jfr1tel', models.CharField(max_length=11, null=True, verbose_name='监护人2联系电话')),
                ('jfr2name', models.CharField(max_length=20, null=True, verbose_name='监护人2姓名')),
                ('jfr2gx', models.PositiveSmallIntegerField(choices=[(2, '父亲'), (3, '母亲'), (4, '爷爷'), (5, '奶奶'), (6, '外公'), (7, '外婆'), (12, '亲哥'), (13, '亲嫂'), (14, '表哥'), (15, '表嫂'), (16, '堂哥'), (17, '堂嫂'), (18, '亲姐'), (19, '亲姐夫'), (20, '表姐'), (21, '表姐夫'), (22, '堂姐'), (23, '堂姐夫'), (24, '伯父'), (25, '伯母'), (26, '叔父'), (27, '婶母'), (28, '舅父'), (29, '舅母'), (30, '姨父'), (31, '姨母'), (32, '姑父'), (33, '姑母'), (34, '其他亲属'), (35, '非亲属')], verbose_name='监护人2与登记人关系')),
                ('jfr2tel', models.CharField(max_length=11, null=True, verbose_name='监护人2联系电话')),
                ('regaddress', models.CharField(max_length=100, null=True, verbose_name='户籍所在地')),
                ('resaddress', models.CharField(max_length=100, null=True, verbose_name='居住所在地')),
                ('resaddressnum', models.CharField(max_length=100, null=True, verbose_name='居住地详细地址')),
                ('stuobj', models.PositiveSmallIntegerField(choices=[(1, '户籍所在地属于划片范围内的适龄人员'), (2, '外省外县进城务工随迁子女（家长务工就业或经商）'), (3, '盘州市内进城务工子女（家长务工就业或经商）'), (4, '烈士子女、驻盘部队的现役军人子女、公安英模和因公牺牲、伤残警察子女'), (5, '参加抗疫最前线的医护人员的子女'), (6, '易地扶贫搬迁子女')], verbose_name='登记对象属性')),
                ('houseoption', models.PositiveSmallIntegerField(choices=[(0, '购房'), (1, '租房'), (2, '自建房')], verbose_name='预登记学生现住房类型')),
                ('operatortype', models.IntegerField(choices=[(0, '未上传资料或未提交'), (1, '提交待初审'), (2, '初审通过'), (3, '审核不通过（不允许再次提交）'), (4, '审核不通过（驳回修改)'), (5, '复审通过'), (6, '复审不通过')], default=0, verbose_name='操作状态')),
                ('publicid', models.IntegerField(default=0, verbose_name='是否公示')),
                ('schoolGrade', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elementary.stu_school_grade')),
            ],
            options={
                'verbose_name': '预登记情况总表',
                'verbose_name_plural': '预登记情况总表',
            },
        ),
    ]
