# Generated by Django 4.1.7 on 2023-02-27 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elementary', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stu_school_grade',
            unique_together={('school', 'grade')},
        ),
    ]
