# Generated by Django 4.1.7 on 2023-03-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementary', '0003_alter_stu_register_table_jfr2gx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_register_table',
            name='jfr1gx',
            field=models.PositiveSmallIntegerField(choices=[(1, '无'), (2, '父亲'), (3, '母亲'), (4, '爷爷'), (5, '奶奶'), (6, '外公'), (7, '外婆'), (12, '亲哥'), (13, '亲嫂'), (14, '表哥'), (15, '表嫂'), (16, '堂哥'), (17, '堂嫂'), (18, '亲姐'), (19, '亲姐夫'), (20, '表姐'), (21, '表姐夫'), (22, '堂姐'), (23, '堂姐夫'), (24, '伯父'), (25, '伯母'), (26, '叔父'), (27, '婶母'), (28, '舅父'), (29, '舅母'), (30, '姨父'), (31, '姨母'), (32, '姑父'), (33, '姑母'), (34, '其他亲属'), (35, '非亲属')], verbose_name='监护人1与登记人关系'),
        ),
        migrations.AlterField(
            model_name='stu_register_table',
            name='jfr2gx',
            field=models.PositiveSmallIntegerField(choices=[(1, '无'), (2, '父亲'), (3, '母亲'), (4, '爷爷'), (5, '奶奶'), (6, '外公'), (7, '外婆'), (12, '亲哥'), (13, '亲嫂'), (14, '表哥'), (15, '表嫂'), (16, '堂哥'), (17, '堂嫂'), (18, '亲姐'), (19, '亲姐夫'), (20, '表姐'), (21, '表姐夫'), (22, '堂姐'), (23, '堂姐夫'), (24, '伯父'), (25, '伯母'), (26, '叔父'), (27, '婶母'), (28, '舅父'), (29, '舅母'), (30, '姨父'), (31, '姨母'), (32, '姑父'), (33, '姑母'), (34, '其他亲属'), (35, '非亲属')], null=True, verbose_name='监护人2与登记人关系'),
        ),
    ]
